### ISSUE TITLE
Missing mapped services. (Skipped channels)

### ISSUE THREAD

**Issue by erbasandrade** [tvheadend/dtv-scan-tables#86]
I have a problem with tvheadend 4.3 using the most recent commit.
Using tvheadend 4.2 after mapping the channels I get 49 ignored channels.
Using tvheadend 4.3 after mapping the channels I get 63 ignored channels.
DVB-S adapter
Star one c2 / c4 satellite. Brazil
70.0 ° W, KU band. https://www.portaleds.com/satelites/listar.php?sat=2900

**Comment by Flole998** [comment]
Not an issue with the scan tables.
